theme:
  active: "89, 120, 81"                # current playing song in list
  banner: "255, 252, 153"                 # the "spotify-tui" banner on launch
  error_border: "241,250,140"          # error dialog border
  error_text: "248,248,242"            # error message text (e.g. "Spotify API
                                       # reported error 404")
  hint: "241,250,140"                  # hint text in errors
  hovered: "89, 120, 81"               # hovered pane border
  inactive: "169, 186, 101"              # borders of inactive panes
  playbar_background: "89, 120, 81"       # background of progress bar
  playbar_progress: "255, 252, 153"      # filled-in part of the progress bar
  playbar_progress_text: "169, 186, 101" # song length and time played/left
                                       # indicator in the progress bar
  playbar_text: "255, 253, 176"          # artist name in player pane
  selected: "255, 254, 196"               # a) selected pane border, b) hovered item
                                       # in list, & c) track title in player
  text: "255, 253, 176"                  # text in panes
  header: "169, 186, 101"                # header text in panes (e.g. 'Title',
                                       # 'Artist', etc.)
